export const GENERAL_BENEFITS = [
  {
    icon: <img src="/internship_images/iso.png" alt="ISO Certified" className="w-14 h-14 object-contain drop-shadow-sm" />,
    title: "ISO Certified Certificate",
    desc: "Internationally recognised certificate for private-sector employment across India.",
  },
  {
    icon: <img src="/internship_images/interview.png" alt="Interview Prep" className="w-8 h-8 object-contain drop-shadow-sm" />,
    title: "Interview Prep PDF",
    desc: "Curated question bank from real front-end and MERN interviews with full answers.",
  },
  {
    icon: <img src="/internship_images/live.png" alt="Recorded Lectures" className="w-14 h-14 object-contain drop-shadow-sm" />,
    title: "Lifetime Recorded Lectures",
    desc: "Lifetime access to all sessions. Re-watch any lesson at any time on the BBS portal.",
  },
  {
    icon: <img src="/internship_images/learning_portal.png" alt="Learning Portal" className="w-10 h-10 object-cover rounded-md drop-shadow-sm" />,
    title: "Dedicated Learning Portal",
    desc: "Personal login, progress tracking, materials, and assignments in one place.",
  },
  {
    icon: <img src="/internship_images/real-life.png" alt="Real Life Project" className="w-10 h-10 object-contain drop-shadow-sm" />,
    title: "Live Deployed Project",
    desc: "A real deployed website on the internet (like DevLinks, TaskFlow, NoteNest).",
  },
  {
    icon: <img src="/internship_images/community.png" alt="Community Access" className="w-10 h-10 object-contain drop-shadow-sm" />,
    title: "BBS Community Access",
    desc: "Doubt support, peer group, and access to the BBS developer network.",
  },
  {
    icon: <img src="/internship_images/resume.jpg" alt="Resume Review" className="w-10 h-10 object-cover rounded-md drop-shadow-sm" />,
    title: "Resume & LinkedIn Review",
    desc: "Resume review and LinkedIn profile guidance from BBS developers.",
  },
  {
    icon: <img src="/internship_images/placement.png" alt="Placement Support" className="w-10 h-10 object-contain drop-shadow-sm" />,
    title: "Placement Support",
    desc: "Job-readiness mentoring and placement assistance from the BBS team.",
  },
];

export const COURSES = [
  {
    id: "html-css-javascript-in-28-days",
    num: "Course 01",
    badge: "Beginner",
    title: "Certified Front-End Development Trainee",
    tagline: "From zero to a live website in four weeks.",
    duration: "28 Days",
    hours: "1 Hour / Day",
    level: "No Prior Experience",
    projects: "1 Live Project",
    wasPrice: "₹5,999",
    price: "₹3,999",
    emi: "or ₹1,400/mo × 3",
    color: "#C8860A",
    waMessage: "Hi! I'd like to enroll in Course 01 (HTML + CSS + JS in 28 Days).",
    stats: [
      { v: "28", l: "Total days of learning" },
      { v: "4", l: "Learning phases" },
      { v: "28", l: "Recorded sessions" },
      { v: "1", l: "Live deployed project" },
    ],
    phases: [
      {
        num: "Phase 01",
        days: "Days 1–7",
        sub: "7 hours total",
        name: "HTML — Structure First",
        topics: ["HTML boilerplate", "h1–h6, p, br, strong, em", "Links & images", "Lists & navigation", "Divs & containers", "Semantic tags", "Forms, inputs, buttons"],
        build: "A fully semantic static profile page with contact form",
      },
      {
        num: "Phase 02",
        days: "Days 8–14",
        sub: "7 hours total",
        name: "CSS — Make It Look Real",
        topics: ["Box model", "Colors & Google Fonts", "Selectors & specificity", "Flexbox (full)", "CSS Grid", "Media queries & responsive", "CSS variables & transitions"],
        build: "A responsive styled landing page — hero, cards, footer",
      },
      {
        num: "Phase 03",
        days: "Days 15–21",
        sub: "7 hours total",
        name: "JavaScript — Make It Respond",
        topics: ["let & const", "Functions & logic", "DOM manipulation", "Events (click, input, keydown)", "Arrays & loops", "Objects & JSON", "Fetch API & async/await", "localStorage"],
        build: "Interactive to-do list with persistence across refresh",
      },
      {
        num: "Phase 04",
        days: "Days 22–28",
        sub: "7 hours total",
        name: "Capstone Build — DevLinks",
        topics: ["Semantic HTML scaffold", "CSS variables theme", "Responsive layout", "Dark/light mode toggle", "Copy-link button (JS)", "Visit counter (localStorage)", "GitHub Pages deployment"],
        build: "DevLinks — a personal link-in-bio page live on the internet",
      },
    ],
    capstone: {
      title: "DevLinks — Personal Link-in-Bio Page",
      desc: "A fully functional, mobile-responsive personal page where students showcase their profile, social links, and bio. Students walk away with a real URL they can share with anyone — a portfolio piece from Day 28.",
      deploy: "GitHub Pages",
      techs: ["Semantic HTML5", "CSS Custom Properties", "Flexbox Layout", "Responsive Design", "Dark / Light Mode Toggle", "JavaScript DOM", "localStorage", "Copy-Link Button", "Free Hosting — GitHub Pages"],
    }
  },
  {
    id: "zero-to-mern-in-65-days",
    num: "Course 02",
    badge: "Absolute Beginner",
    title: "Certified Software Engineer",
    tagline: "No experience needed. Full-stack developer by Day 65.",
    duration: "65 Days",
    hours: "2 Hours / Day",
    level: "No Prior Experience",
    projects: "Full Stack + Deployed",
    wasPrice: "₹11,999",
    price: "₹7,999",
    emi: "or ₹1,600/mo × 5",
    color: "#C8860A",
    waMessage: "Hi! I'd like to enroll in Course 02 (Zero to MERN in 65 Days).",
    stats: [
      { v: "65", l: "Total learning days" },
      { v: "9", l: "Distinct learning phases" },
      { v: "65", l: "Recorded sessions" },
      { v: "1", l: "Full-stack app, live deployed" },
    ],
    phases: [
      {
        num: "Phase 01",
        days: "Days 1–7",
        sub: "HTML",
        name: "HTML — Building the Skeleton",
        topics: ["Boilerplate & browser", "Text & headings", "Links & images", "Lists & nav", "Divs & semantic HTML", "Forms & inputs", "Tables (data only)"],
        build: "Semantic static recipe page — all HTML, no styling yet",
      },
      {
        num: "Phase 02",
        days: "Days 8–16",
        sub: "CSS",
        name: "CSS — Styling, Layout, Responsive",
        topics: ["Box model", "Typography & Google Fonts", "Selectors & specificity", "Flexbox", "CSS Grid", "Media queries", "CSS variables", "Transitions"],
        build: "Responsive landing page — hero, 3 feature cards, fully mobile ready",
      },
      {
        num: "Phase 03",
        days: "Days 17–27",
        sub: "JavaScript",
        name: "JavaScript — Logic, DOM, APIs",
        topics: ["Variables & types", "Functions & arrow fns", "DOM manipulation", "Events", "Arrays & loops", "Objects & JSON", "Fetch & async/await", "localStorage", "ES6 modules", "Classes", "Git & GitHub basics"],
        build: "Persistent to-do list + public GitHub repos pushed",
      },
      {
        num: "Phase 04",
        days: "Days 28–34",
        sub: "Node.js",
        name: "Node.js — Servers and Modules",
        topics: ["Node runtime", "require & module.exports", "npm & nodemon", "fs module", "Raw http server", "dotenv", "Error handling"],
        build: "CLI tool + raw Node server with .env config",
      },
      {
        num: "Phase 05",
        days: "Days 35–44",
        sub: "Express.js",
        name: "Express.js — Full REST API",
        topics: ["Express routing", "Middleware", "Router files", "REST API design", "Error middleware", "CORS", "Validation", "Multer uploads"],
        build: "10-endpoint REST API for Users + Products",
      },
      {
        num: "Phase 06",
        days: "Days 45–52",
        sub: "MongoDB",
        name: "MongoDB + Mongoose — Cloud Database",
        topics: ["Atlas free cluster", "Mongoose connect", "Schema & Model", "CRUD operations", "Validation & defaults", "populate()", "Filter / sort / paginate", "Aggregation basics"],
        build: "API now persists to MongoDB Atlas — no more in-memory data",
      },
      {
        num: "Phase 07",
        days: "Days 53–57",
        sub: "Auth / JWT",
        name: "JWT Authentication — Real Login System",
        topics: ["Sessions vs JWT", "bcrypt hashing", "Register & login endpoints", "jwt.sign() & verify()", "Auth middleware", "User-owned resources"],
        build: "Complete register/login system with protected note routes",
      },
      {
        num: "Phase 08",
        days: "Days 58–63",
        sub: "React",
        name: "React — Frontend Connected to Your API",
        topics: ["Vite setup", "Components & props", "useState & useEffect", "React Router v6", "AuthContext", "Axios + token interceptor", "Form submission"],
        build: "React frontend wired to Express API — login & notes working",
      },
      {
        num: "Phase 09",
        days: "Days 64–65",
        sub: "Deploy",
        name: "Deploy — Put It on the Internet",
        topics: ["Push to GitHub", "Deploy backend to Render", "Deploy frontend to Vercel", "CORS in production", "Environment variables"],
        build: "NoteNest — live full-stack app on the internet, Day 65",
      },
    ],
    capstone: {
      title: "NoteNest — Full Stack Notes App",
      desc: "A complete full-stack notes application. Users register, log in, and manage their own personal notes. JWT protects all routes. MongoDB stores all data. React handles the frontend. Deployed live and fully functional by Day 65 — a real portfolio piece.",
      deploy: "Render + Vercel",
      techs: ["HTML + CSS + JS", "Node.js", "Express REST API", "MongoDB Atlas", "Mongoose", "JWT Auth", "bcrypt", "React + Vite", "React Router v6", "Axios", "Context API", "Render + Vercel"],
    }
  }
];
